apiVersion: v1
kind: Pod
metadata:
  name: h1
  labels:
    apptype: frontend
    environment: dev
spec:
  nodeSelector:
    hardware: highspec
  containers:
  - name: first-container
    image: nginx
    ports:
    - containerPort: 80