apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    apptype: frontend
    environment: production
spec:
  containers:
  - name: first-container
    image: nginx
    ports:
    - containerPort: 80
 